---
title: RCoinAPI - Part 1
author: Ramshreyas Rao
date: '2021-07-05'
slug: []
categories:
  - Crypto
tags: []
lastmod: '2021-07-05T17:22:53+05:30'
keywords: []
description: ''
comment: no
toc: no
autoCollapseToc: no
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: no
mathjaxEnableSingleDollar: no
mathjaxEnableAutoNumber: no
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
---

# An R package for the CoinAPI.io REST API

This is the first in a series of posts detailing my first R package :smile:, providing access to CoinAPI.io's REST API. 

The goal with this package is to closely match the wonderful [Quantmod](https://cran.r-project.org/web/packages/quantmod/quantmod.pdf), so that you can add Crypto to your Quant workflow using CoinAPI data with as little pain as possible.

In this series, we'll use RCoinAPI to get Crypto data, create a trading strategy, and backtest it with [quantstrat](https://github.com/braverock/quantstrat). :sunglasses:

## Before you start

Documentation: https://github.com/Ramshreyas/rcoinapi

## Requirements

A working R installation with [devtools](https://www.r-project.org/nosvn/pandoc/devtools.html) installed.

An API key: https://www.coinapi.io/pricing?apikey. The free one will do for our tutorial.

A basic understanding of [Crypto]()

A basic understanding of [indicators]()

Access to :coffee:

## Installation

<!-- You can install the released version of rcoinapi from [CRAN](https://CRAN.R-project.org) with: -->

<!-- ``` r -->
<!-- install.packages("rcoinapi") -->
<!-- ``` -->

You can install the development version from [GitHub](https://github.com/) with:

``` r
install.packages("devtools")
devtools::install_github("Ramshreyas/rcoinapi")
```
## Setup

Load the library

``` r
library(rcoinapi)
```

Set your API key (Get your free API key at https://www.coinapi.io/pricing?apikey)

``` r
setApiKey("XXXXXXXXXXXXXXX")
```

Test if it's working by getting the list of exchanges that CoinAPI gives access to

``` r
getExchanges()
```

## THIS IS NOT FINANCIAL ADVICE

\'nuff said. :triumph:

## Your first crypto trading strategy

Any trading strategy helps you make only two decisions:

- When to buy
- When to sell

That's. It. If your strategy enables you to buy lower than you sell more often than not, you are making money (Ignoring some pesky but important funding issues that can bankrupt you before you make money etc... but we're not going to dwell on it). 

Probably the most commonly (and therefore the least likely to :full_moon:) strategy is the [Golden/Death cross](https://academy.binance.com/en/articles/golden-cross-and-death-cross-explained):

- BUY when the 50-day moving average crosses above the 200-day moving average
- SELL when the 50-day moving average crosses below the 200-day moving average

Let's test this against historical data of BTC/USD and see how it works!

### Step 1 - get historical prices of BTC. 

Let's get historical prices of BTC/USD from Binance

``` r

